### ISSUE TITLE
Api method getUserPurchase wrong namespace

### ISSUE THREAD

**Issue by guillaumek** [Stamplia/stamplia-php#1]
'getUserPurchase' => array(
    'method' => 'get',
    'url' => '/users/{userId}/purchases/{purchaseId}',
    'parameters' => array('userId', 'purchaseId'),
    'namespace' => 'purchases',
)

seems that the expected namespace is 'purchase'

**Comment by Stamplia** [comment]
This has been corrected on the API side and the namespace is now 'purchases' as expected
